export const dataConstants = {
  FETCH_DATA: 'FETCH_DATA',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',

  FETCH_EXTENDED_DATA: 'FETCH_EXTENDED_DATA',
  FETCH_EXTENDED_DATA_SUCCESS: 'FETCH_EXTENDED_DATA_SUCCESS',
  FETCH_EXTENDED_DATA_FAILURE: 'FETCH_EXTENDED_DATA_FAILURE',
};
